[profile.dev]
lto = true
debug = true
strip = false
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[profile.release.package."*"]
strip = true
opt-level = 3

[target.x86_64-unknown-linux-musl]
linker = "/usr/bin/clang"
rustflags = [
  "-Zshare-generics=y",
  "-C", "link-arg=--ld-path=/usr/bin/mold"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
  "-Zshare-generics=y",
  "-C", "link-arg=--ld-path=/usr/bin/mold"
]
